### ISSUE TITLE
FastScroller

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/FastAdapter#1]
* find a good implementation for a fastScroller to add as nice addon

**Comment by mikepenz** [comment]
Will be independent of the `FastAdapter`

Possible solutions:
* https://github.com/plusCubed/recycler-fast-scroll
*

**Comment by hendrawd** [comment]
Is the fast scroller function working as expected here? Because i downloaded the application from google play, but the fast scroller function is not working. The activity that i choose is SimpleItemList Sample(FastScroller, Filter, Drag&Drop)

<img src="https://user-images.githubusercontent.com/9481791/26880977-4c79f590-4bc0-11e7-81f8-00f215de83af.jpg" alt="screen shot" width="300px"/>

**Comment by mikepenz** [comment]
@hendrawd true that sample no longer contains the fastscrolling

**Comment by hendrawd** [comment]
But is it still support fast scrolling? Especially with fast scroller indicator/thumbnail/preview like alphabet section indexer from listview?

**Comment by mikepenz** [comment]
well the `GenericItem sample` still has the thing in. The FastScrolling was always an external library, and I just show compatiblity in the sample. It is in no way related to that project

**Comment by hendrawd** [comment]
Yes i checked it and it's working, thanks a lot!
