### ISSUE TITLE
One more advice

### ISSUE THREAD

**Issue by artests87** [mikepenz/FastAdapter#119]
Hi!
Maybe you'll do a feature.
I have expandable item and some Sampleitem internal, and if I select internal sampleItem and close the ExpandableItem my selected SampleItem don't unselected, before I will click on it again.
Thanks.

**Comment by artests87** [comment]
And saveinstance after minimize and rotate...

**Comment by mikepenz** [comment]
@artests87 sorry I am not quite sure what you want

**Comment by artests87** [comment]
Sorry for my bad English(
I'll try explain it step by step.
Why we need the view?
For example, we want to show a list with items.
Then, the user select needful items. Some of them internal items (SampleItems in ExpandableItem). Now, when the user select internal items, close the ExpandableItem (parent directory for select SampleItems) and open the ExpandableItem again, he see the SampleItems don't select. He needs select the SampleItems again.

Eventually, when the user rotate (minimaze) phone - all Items deselect and he needs select all again.

**Comment by artests87** [comment]
If I want to select some Items before open and show the adapter, I can't to it with internal SampleItems.
I can select all except internal items. Internal items didn't select...

**Comment by mikepenz** [comment]
@artests87 the `FastAdapter` is already able to keep the selection and the expanded state upon screen orientation change etc.. See the `SimpleItemListActivity`
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.java#L114

Regarding your second topic. 
That was a decision I made when I started the `FastAdapter` so it works as expected, and I have no plancs to change this behavior as it will have other bad side effects. 

So a more technical insight for this:
The `FastAdapter` keeps track of the position (not the item) for selections, and the expanded state. This is a really important thing to know, because this allows to `FastAdapter` to stay high performant even with Integer.MAX_INT items in it. So what are the pro points for this decision:
The `FastAdapter` will stay fast for selections no matter what happens, it is really fast to get the current selections, to store and restore the state, and so on. And there is no change in performance the more items we have. 
The cons for this implementation are, that your requirement can't be handled by the `FastAdapter` as it can only keep track of selections for items which are currently dispalyed. So which have a position within the `FastAdapter` (SubItems are definitly not in the list and so have no position) 
So I could have chosen to just keep the selection within the item itself, but it will have bad sideeffects. Every function which needs to keep track of the selection, expandable state will always have to iterate over all the items in the list and this will provide worse performance the more items the list contains. 

The `FastAdapter` provides all callbacks and listeners, so you can keep track of selections of sub items in for your project. And you can select them again as soon as the event is triggered that a sub selection is opened again. 



I hope this detailed description clears things up

**Comment by mikepenz** [comment]
@artests87  you might be interested in this huge new feature: https://github.com/mikepenz/FastAdapter/issues/122

**Comment by artests87** [comment]
Hi, Mike!
Thanks a lot.
But I didn't can build my project with new feature, because Error:(27,
13) Failed to resolve:
com.mikepenz:fastadapter-extensions:1.5.0-SNAPSHOT
<a href="openFile:C:/JAVA/Android/QOL/app/build.gradle">Show in
File</a><br><a href="open.dependency.in.project.structure">Show in
Project Structure dialog</a>
However, I had realised that feature with List, where I mark selected
items, with inner items.
If you'll say me how to add new feature in my project, I'll test it,
with pleasure.
Best regardes,
Andrei

2016-04-30 23:38 GMT+03:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
You need to have the snapshot repository as repo in your root build.gradle

**Comment by mikepenz** [comment]
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }

**Comment by artests87** [comment]
I got it.
Thanks a lot.
In your test app new feature works execellent)

2016-05-01 15:58 GMT+03:00 Mike Penz <notifications@github.com>:
