### ISSUE TITLE
View config from host

### ISSUE THREAD

**Issue by alashow** [mikepenz/FastAdapter#127]
Hello, thanks for the great library!

I have like this usage case: some items view visibility depends on value which is defined in host activity/fragment.

It might be not only visibility, but other things too - text color/size, different design etc.

In normal adapter, it can be done with adding custom field to adapter (which can be configured with initializer, setters etc).

Any suggestions?

Thanks.

**Comment by mikepenz** [comment]
@alashow I am not quite sure what your issue is. 

You write your item, it can have any properties any settings whatever you want. You can set them. And the view will use them and display them. If all items should have more or less a "configuration". Then you can create a "configuration" object. Pass it to the item, so all have a reference to the same "configuration" object. And If you change this object. Notify the adapter all items will change. 

Best, 
Mike

**Comment by alashow** [comment]
Thanks!
