### ISSUE TITLE
StickyHeader + SwipeItem bug

### ISSUE THREAD

**Issue by dexion** [mikepenz/FastAdapter#131]
Thanks for your libs!

Without StickyHeader all works fine. 
![fine](https://cloud.githubusercontent.com/assets/177283/15203136/541b65e8-1833-11e6-8d2f-9ee782f3fa99.gif)
With StickyHeader some bugs: header dismiss with first item from group, background layout not visible for swiped item.
![bug](https://cloud.githubusercontent.com/assets/177283/15203252/4d659b28-1834-11e6-866f-5df9edbd28db.gif)

Changes in code are:
```java
//rv.setAdapter(itemAdapter.wrap(fastAdapter));
rv.setAdapter(stickyHeaderAdapter.wrap(itemAdapter.wrap(headerAdapter.wrap(fastAdapter))));

//this adds the Sticky Headers within our list
final StickyRecyclerHeadersDecoration decoration = new StickyRecyclerHeadersDecoration(stickyHeaderAdapter);
rv.addItemDecoration(decoration);
//so the headers are aware of changes
stickyHeaderAdapter.registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
            @Override
            public void onChanged() {
                decoration.invalidateHeaders();
            }
        });
```

All code from your sample app.
Versions:
```
compile('com.mikepenz:fastadapter:1.4.5@aar') { transitive = true }
compile('com.mikepenz:itemanimators:0.2.4@aar') { transitive = true }
compile 'com.mikepenz:fastadapter-extensions:1.4.5@aar'
compile 'com.mikepenz.thirdparty:stickyheadersrecyclerview:0.4.4-SNAPSHOT@aar'
```

Seems problem is in `StickyHeaderAdapter` but I can't investigate it

**Comment by mikepenz** [comment]
@dexion I am not sure if this can be fixed. The  `StickyHeaderAdapter` uses an `Decorator` to display the header above the item. The project used in the sample is the following:
https://github.com/timehop/sticky-headers-recyclerview

I just added a small animation optimizations (that's why it has a SNAPSHOT version)

I can't give support for external libraries. And it seems they no longer maintain the project. There may be other `StickyHeader` implementations which deal a bit better with the above usecase

**Comment by Rainer-Lang** [comment]
@dexion Maybe this lib helps: https://github.com/ShamylZakariya/StickyHeaders
When you tried it, please give a short feedback. Thanks.
