### ISSUE TITLE
FastAdapter for classes who already extends from a base parent

### ISSUE THREAD

**Issue by duyngn** [mikepenz/FastAdapter#143]
Hi Mike,

Just wondering how I could use FastAdapter to apply to child classes that already extends a common base class.

Suppose I have a collection of sport players... BasketballPlayer, FootballPlayer, SoccerPlayer, BaseballPlayer, GolfPlayer.  They each could inherited from a common class SportPlayer, which could include many shared properties such as Name, Location, Height, Weight, Bio, etc.  However, each sport player type differs on how their stats are being tracked... "Par" stat of a GolfPlayer would not exist in other classes.

Let's suppose a list of ALL players (regardless of their sport) needs to be displayed... it should render the rows differently depending on which sport they play.  We're talking about multiple layout types in the same list.

I imagine that each specific sport player concrete class would provide its own type of ViewHolder, type, and layout, as well as how it should bind its views.  However, we're facing double inheritance: Extending from the base class and extending from AbstractItem.

**Comment by mikepenz** [comment]
@duyngn hi 

If you can't extend from the `AbstractItem` you either could just implement the `IItem` interface, or you choose to split up `Model` and `Item` as shown in the `MultiTypeGenericItemActivity`
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java

It just uses one model class, but you can easily change it to allow different model types too, and you can then simply define which item to choose for which model or any logic which is used.

**Comment by duyngn** [comment]
Thanks Mike,

I think I got it working... more of an exercise to mess with your library :)

public abstract class SportPlayer<Item extends AbstractItem<Item, VH>, VH extends RecyclerView.ViewHolder> extends AbstractItem<Item, VH> {}

public class BasketballPlayer extends SportPlayer< BasketballPlayer, BasketballPlayer.ViewHolder> {}
public class GolfPlayer extends SportPlayer< GolfPlayer, GolfPlayer.ViewHolder> {}

This will enforce the concrete player classes to implement:
public int getType()
public int getLayoutRes()

But it won't enforce the concrete player classes to implement:
public void bindView(ViewHolder vh)

That's because AbstractItem already has an implementation of this function.
So a manual override for bindView() must be done in each concrete player class.

**Comment by shehabix** [comment]
@mikepenz can you add an example of how it to allow different model types?, even a basic example here?

I have the following:

```java
public abstract class BaseItemWrapper<Item extends BaseItemWrapper<?, ?>, VH extends RecyclerView.ViewHolder> extends AbstractItem<Item, VH> {

}
```
``java
public class NewsItemWrapper extends BaseItemWrapper<NewsItemWrapper, NewsItemWrapper.ViewHolder> {
}
```
```java
public class AdItemWrapper extends BaseItemWrapper<AdItemWrapper, AdItemWrapper.ViewHolder> {
}
```
now how create the GenericItemAdapter out of this?

**Comment by or-dvir** [comment]
i just came across the same problem and found this thread, but for some reason i couldnt really understand the solution offered and also failed implementing it by trying to copy it.

i have however found a different, less complicated (at least in my mind) solution.
@mikepenz please tell me if you think this is a "bad" way to solve the issue.

here is the declaration of my base (or "father") class:
`public class MyItem<T extends MyItem, VH extends RecyclerView.ViewHolder> extends AbstractItem<T, VH>`

and here is the definition of the inherited (or "son") class:
`public class MyItemAlso extends MyItem<MyItemAlso, MyItemAlso.ViewHolder>`

thats it!

the "father" class would have to override the methods "getType" and "getLayoutRes" which in my case don't have any meaning because "MyItem" is simply used to hold shared information and only classes extending it are to be displayed in the recyclerView. so in my case these methods can simply call the "super" methods.
however if you wish for the "Father" class to be displayed as an item in the recyclerView, simply implement these methods as you were with a normal AbstractItem, and the same goes for any inherited (or "son") classes

**Comment by mikepenz** [comment]
@or-dvir it's totally fine. In general the type definitions in Java will help you while coding the most, the code which is executed in the end does not care much about it anyways.
