### ISSUE TITLE
How to get the textview from an item?

### ISSUE THREAD

**Issue by Spotik** [mikepenz/FastAdapter#161]
Hi there,

How can I change one atribute for an item when I click on it?

I want to change the color of the textview when the user select an item on multiselect. How can I have access to the views inside the itens?

And if I delete itens on a list and press back before the snackbar is dismissed, the item is not deleted when I back to the list... there's a fix for this?

**Comment by mikepenz** [comment]
@Spotik if you change an attribute you have to call a `notifyAdapterItemChanged` event. Which will call the `bindView` again. 
In general you should not directly access the view as this is all handled by the `RecyclerView` and optimal caching is not possible otherwise. 
What you can do is that you get the view from the `onClick` event and search for your view, and that you update it then. Also remember that the `bindView` has to handle the same logic otherwise you get inconsistent behavior. 

If you delete an item you also have to call `notifyAdapterItemRemoved()` (and all those notify methods have to be called on the main UI thread)
