### ISSUE TITLE
select() method ignores the selectable flag and so selects section items

### ISSUE THREAD

**Issue by RedMillLtd** [mikepenz/FastAdapter#166]
Am I correct in saying that the select all function called select() selects the all items whether they are set to selectable or not?

Should the select(int position, boolean fireEvent) method include a check for selectable or have I missed something?

Thanks in advance

**Comment by mikepenz** [comment]
@RedMillLtd that's the intended behavior, as the programmatic methods allow you to select items which are not selectable. 
That decision was made because in some applications it's necessary to be able to select even if the item is in general not selectable via user interaction. 

Would be an improvement to add a flag for this on the `select()` method

**Comment by Rainer-Lang** [comment]
I think - yes

**Comment by RedMillLtd** [comment]
Thank you very much for the quick response.  It might be nice to have in the future.

**Comment by mikepenz** [comment]
this feature is available in the v`1.6.1-SNAPSHOT` (which is on the maven central snapshot repository) it will be included in the next release. 

You can already test it and use it with the above named snapshot. don't forget to add the snapshot repository to your repos.
