### ISSUE TITLE
SubItems - updating

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#284]
I've a general question to that, I'm, currently writing functions to add/remove items... I've checked the `notifyAdapterSubItemsChanged` function and see that it just removes all sub items from the adapter and readds them afterwards.

Is there any reason that you did not implement add/remove functions for sub items yet? Other than that you did not need them yet?

I want to add add/remove functionality for sub items and wanted to know if following (based on an add method) would work or if I would need to think about other things as well:

**Adding**
* if the header is collapsed, I just add the new sub item to the header (maybe notify the header, the user should deside this, depending on if the header displays it's sub item counts for example), that's all
* if the header is expanaded, I just add the new sub item to the headers sub items, then I call `FastItemAdapter.add(int position, Item... items) ` with the current global position of the new sub item and call `notifyAdapterItemInserted` with the new sub items global index

Is that really all?

**Comment by mikepenz** [comment]
@MFlisar it was never added because I saw a bit too much special handling in this functionality. And I didn't expect this to be such a core functionality in some cases. 

In addition I saw no real usecase of having the same methods of adding, ... as for normal items. 

But that does not mean other people don't need it too. 

As of your initial idea of implementing this. 
- For the first point it's true
- For the second, you will also have to update the subitems count in the map where we remember how many subitems are shown for a specific parent. and you have to check if a specific global position is within a subitem list. I would recommend an additional method of doing this. so not with the normal `add` method. as it may break things or cause confusion
