### ISSUE TITLE
how can i get the adapter multiselect state?

### ISSUE THREAD

**Issue by uiiang** [mikepenz/FastAdapter#297]
how can i get the adapter multiselect state?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L207

**Comment by uiiang** [comment]
sorry
 i don't mean change to multiselect , but estimate current  if may been multiselect

**Comment by mikepenz** [comment]
So you mean if the CAB is shown? otherwise you can just get the selected items, which will return your multiple positions if the user selected more than one

**Comment by uiiang** [comment]
can i get  the adapter multiselect  state is yes or not, before user selected?

**Comment by mikepenz** [comment]
@uiiang if you use hte CAB you can check if it is active: https://github.com/mikepenz/FastAdapter/blob/3b5f1af9702762e84cef8e6b9d8abcbf93fd1958/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java#L69

Otherwise there is no getter for the isMultiselect field of the fastadapter

**Comment by uiiang** [comment]
thanks，i' ll try your way
