### ISSUE TITLE
call unbindView of items when recyclerview destoryed

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#323]
is posible that call `unbindView` of binded items when recyclerview destoryed ?
i need it for glide and image loading, when activity/recyclerview destoryed

**Comment by FabianTerhorst** [comment]
The FastAdapter is using the default behavior. 
"Called when a view created by this adapter has been recycled.
A view is recycled when a RecyclerView.LayoutManager decides that it no longer needs to be attached to its parent RecyclerView. This can be because it has fallen out of visibility or a set of cached views represented by views still attached to the parent RecyclerView. If an item view has large or expensive data bound to it such as large bitmaps, this may be a good place to release those resources.
RecyclerView calls this method right before clearing ViewHolder's internal data and sending it to RecycledViewPool. This way, if ViewHolder was holding valid information before being recycled, you can call getAdapterPosition() to get its adapter position."
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onViewRecycled(VH)
