### ISSUE TITLE
Filtering on a thread

### ISSUE THREAD

**Issue by frmz** [mikepenz/FastAdapter#336]
Sometimes my implementation of "IItem" has not all the info loaded as soon as i add it, some (like images) are being loaded only when displayed. Now, if i want to filter based on a field that might require some time to be loaded i currently need to do the search on my own and then set the adapter again with the items i filtered. It would be nice to allow filtering on a thread so then out of the UI a list of matching items is prepared and then back in UI thread the adapter is actually filtered. 

Is this too complex / out of library scope?

**Comment by mikepenz** [comment]
@frmz this seems to be out of scope of this library. That's a rare usecase of having it already sorting  on lazy fields. You may be able to achieve it with the built in filter already, but I am not sure. 

Otherwise you have to implement this on your own. Perhaps you like to do a PR at some point if you figure it out ;)
