### ISSUE TITLE
Gson Deserialization is not working on Model extends AbstractItem<T1,T2>

### ISSUE THREAD

**Issue by chanonly123** [mikepenz/FastAdapter#363]
Cannot deserialize
public class Category extends AbstractItem<Category, Category.ViewHolder>

**Comment by mikepenz** [comment]
@chanonly123 then you probably should use the `Generic` approach. Which splits apart item and model:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/GenericItemActivity.java

**Comment by chanonly123** [comment]
Awesome, Thanks

**Comment by or-dvir** [comment]
@chanonly123 i just ran into a similar problem but my problem is that my entire app is already built on the basis of AbstractItem and rewriting it would be a major pain the butt...
is that how you ended up fixing it or did you find anothe way?
because i found that recreating the items on startup also fixes the problem (or so it seems). on the one hand its longer (and perhaps unneccessary) running time, but on the other hand i just had to add a couple of for loops and that was it
