### ISSUE TITLE
Toggle from disable to enable doesn't work with HeaderAdapter

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#406]
[Here](https://github.com/CTFMcGill/CTF-Android/blob/7218df5422d5b6b96b88e9b500eba5eb3f8d8a16/CTF/src/main/java/ca/mcgill/science/ctf/iitems/UserHeaderItem.java#L161) is the source for what I'm working with.

```java
adapter.withOnPreClickListener((v, adapter1, item, position) -> {
	// consume otherwise radio/checkbox will be deselected
	return true;
});
adapter.withItemEvent(new UserColorClickEvent() {
	@Override
	public void onClick(View v, int position, FastAdapter<UserHeaderItem> fastAdapter, UserHeaderItem item) {
		CLog.e("Pre %b %d %d", item.isSelected(), fastAdapter.getItemCount(), fastAdapter.getPreItemCount(position));
		fastAdapter.toggleSelection(position); //TODO toggle isn't working
		CLog.e("Post %b", item.isSelected());
		setColourPrinting(fragment, item.isSelected());
	}
});
```

The listener is simple and is based off of the checkbox one. If it starts off as unselected, the toggle works.

```
Pre false 98 0
Post true
```
However, if it starts off as selected, the item is still selected after the toggle.

```
Pre true 98 0
Post true
```
 I have tested disable(position) and that works, so that part isn't the issue. Is there something with the list of selected items that isn't updating? I add it using [withSetSelected](https://github.com/CTFMcGill/CTF-Android/blob/7218df5422d5b6b96b88e9b500eba5eb3f8d8a16/CTF/src/main/java/ca/mcgill/science/ctf/iitems/UserHeaderItem.java#L112)

**Comment by mikepenz** [comment]
well if you started "selected" the problem is that the internal "selection" state is not set in the FastAdapter.. For faster access to the number of selected items (without iterating the whole list) the FastAdapter keeps track of this for you. 

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L64

If you use the alternative StateManagment this wouldn't be an issue. 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L254

```java
withPositionBasedStateManagement(false)
```

**Comment by AllanWang** [comment]
Ah oops. Wasn't aware that the internal selection wasn't being set with with selected. Thanks
