### ISSUE TITLE
Force call unbindView when destroy activity

### ISSUE THREAD

**Issue by danielpassos** [mikepenz/FastAdapter#428]
I'm running some handler/runnable inside of my ViewHolder and wanna stop it when the activity is destroyed. There is some way to call/force unbindView when activity is destroyed?

**Comment by mikepenz** [comment]
These methods are called by the `RecyclerView` 

It is not really clever to have some runnables running within a viewholder, as it is reused all the time while scrolling.

**Comment by danielpassos** [comment]
@mikepenz I totally agree with you, but, but, but 🙈 I need to run a "progress"/"timer".

![device-2017-05-22-231512](https://cloud.githubusercontent.com/assets/13337/26335945/b8906fa2-3f45-11e7-9e43-d0a63227fe94.png)

**Comment by mikepenz** [comment]
Well but even in this situation there should be no runnable or handler within the view, the problem is that you can't just handle the scrolling which will result in many open handlers / runnables. 

The way how this should be done is by using the notify method. 

There is the way to notify the adapter about changes, providing a payload, that payload can be anything, like the value which you want to display. So the updating and so on happens outside the list, and you notify the items about the change of their view. And I suppose those progressbars all should be at a different value, if they are all equal re-consider the design of having it displayed only once ;)

(beside that as it seems you do a 2FA app, you know authy?)

**Comment by mikepenz** [comment]
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemChanged(int, java.lang.Object)

otherwise you can possibly check: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/IItem.java#L145

other than this I guess you should use the payload variant, as it is the safest. the adapter itself won't notify all items at the stop of your activity (as far as I know)
