### ISSUE TITLE
Weird problem with Firebase/different Threads

### ISSUE THREAD

**Issue by bernaferrari** [mikepenz/FastAdapter#480]
Hey! 

I love so much this library I'm including it in all my projects recently - including at the job! Today I had a problem, and after a few hours thinking and tinkering, I just can't figure out by myself what is happening in the code. Below is the code, simplified, in Kotlin. If anyone doesn't understand it, feel free to ask, I can translate back to Java.

The code is simple: I want to populate the colorsList (and, consequently, the FastAdapter) with data coming from Firebase. The collectData function will transform and split the Firebase data in a way the FastItemAdapter understands. However, nothing works if I remove one (or the 3) of the commented lines at initDemoList below. I tried putting things in the UI thread and all the possible variations I can think of, this was the only way that it worked.. I also read a lot of the Issues in this repository, tried a bunch of fixes, but nothing really worked.

Could someone please help me in this? It makes no sense for me.
If you need/want more code, just ask. There is nothing secret here.

```
internal class FragClass : Fragment() {
    var colorsList = ArrayList<AdapterCulto>()
    var fastAdapter: FastItemAdapter<AdapterCulto> = FastItemAdapter()

    // Firebase object
    private val mylistener = object : ValueEventListener { 
        override fun onDataChange(dataSnapshot: DataSnapshot) {
            dataSnapshot.children.forEach { collectData(it.value as Map<*, *>) }

            activity.runOnUiThread{ fastAdapter.add(colorsList) }
        }
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
    ...
        initDemoList(view)
        return view
    }

    private fun initDemoList(v: View) {
        val recyclerView = v.findViewById(R.id.recycler3) as RecyclerView
      ...
        recyclerView.adapter = fastAdapter
        
        val title = "a"
        val id = "b"
        val views = "c"
   
        colorsList.add(AdapterCulto(title, id,views)) // If I remove this, or the colorsList.clear() below, it will stop working  (fragment show white background only).
        fastAdapter.add(colorsList) // If I remove this line of code, it will stop working (fragment show white background only)
        colorsList.clear()

        val database = FirebaseDatabase.getInstance()
        val myRef: DatabaseReference = database.getReference("cultos")
        myRef.addListenerForSingleValueEvent(mylistener)
    }

    private fun collectData(users: Map<*, *>) {
        val title = users["titulo"].toString()
        val id = users["id"].toString()
        val views = users["views"].toString()
   
     colorsList.add(AdapterCulto(title, id, views))
    }
}

```

**Comment by mikepenz** [comment]
@bernaferrari well I guess the problem in this case is that (I think) you assume the `FastAdapter` could automatically update the list as soon as you add items to the `colorList` that's not the case. 
The `FastAdatper`'s `ItemAdapter` keeps it's own list internal to hold the references to the items, and you have to call `add`, `remove`, `set`, ... on the `ItemAdapter` so that everything can be notified correctly. 

See the code for add: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L344

**Comment by bernaferrari** [comment]
Yeah, but if you look at:
**activity.runOnUiThread{ fastAdapter.add(colorsList) }**
This is precisely what I am doing, right? I tried changing to `set` but still got the same problem. The code is just unable to run without this:

```
colorsList.add(AdapterCulto(title, id, views))
fastAdapter.add(colorsList)
colorsList.clear()
```

With this, it is running fine, even without the `activity.runOnUiThread`. I just don't understand what is happening to make these 3 lines absolutely necessary..

**Comment by mikepenz** [comment]
@bernaferrari I do not use Firebase, but I'd guess something with the timing, or the amount of the callbacks might confuse the RecyclerView or its RecyclerView.Adapter. But honestly I don't know. 

You might want to also try to not use the same list for everything. Just add the single items directly to the adapter in the `onDataChange` instead of going via the colorsList

**Comment by bernaferrari** [comment]
I rewritten everything 3 times, the bug was showing even at AsyncTasks, but it has suddenly gone!
Thanks for your fast help!!

**Comment by mikepenz** [comment]
Awesome :)

**Comment by bernaferrari** [comment]
BTW, thanks for the last advice, I will update my apps with this great practice!
