### ISSUE TITLE
Migration guide - missing change

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#599]
Small issue, as auto complete helps in this case

`com.mikepenz.fastadapter.commons.items.AbstractExpandableItem` must be changed to `com.mikepenz.fastadapter.expandable.items.AbstractExpandableItem` is missing

additonally, what happened with `adapter.withPositionBasedStateManagement(boolean)`?

**Comment by mikepenz** [comment]
v3 only has the `identifier` (so the new approach) based state management. 

The old position based approach was removed as it was quite a lot of overhead of development, and providing none vs just a very tine speed enhancement. and it would make expandable handling very complex (well basically impossible :D because remembering a selection for something which has no position is not doable)

**Comment by MFlisar** [comment]
Ok thanks, this answers my question. So this small info should be added to the migration guide for others as well

**Comment by mikepenz** [comment]
You might want to open a PR for it ;)
