### ISSUE TITLE
Expandable item sample in Kotlin

### ISSUE THREAD

**Issue by markic22** [mikepenz/FastAdapter#624]
## Generics in kotlin
This is not issue with library per se, but I'm having trouble with implementing ExpandingItems, or to be more precise with generics and extending classes. I have managed to change code to kotlin, but I'm having difficulties with Finite bound restriction in Kotlin. General problem and it's solution is described [here](https://stackoverflow.com/a/46682882), but I was not able to implement it in expandable and subItem example.

Did somebody already tried to do that and can share solution?
In perticular I have those 2 files in mind https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.java
and 
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubItem.java

I would appreciate any help or guidance you guys may provide :)

**Comment by mikepenz** [comment]
I can not give Kotlin support sorry. And I think here is not the place for Kotlin questions. This issue sections is for issues with the library itself. If kotlin has issues with java generics it should be fixed on kotlin side :(

**Comment by mikepenz** [comment]
perhaps @AllanWang or @FabianTerhorst have suggestions as they use kotlin

**Comment by AllanWang** [comment]
The stack overflow reference explains it pretty well. Java supports cyclic generics whereas kotlin does not.

The issue is namely in `ISubItem` which depends on `IExpandable`, which depends on `ISubItem` again.

One solution would be to declare a self reference as mentioned in the SO, but that needs to be done in the library (and won't really be pretty).

For me personally, I just wrote my own view allowing for expansion, like [so](https://github.com/AllanWang/KAU/blob/dev/about/src/main/kotlin/ca/allanwang/kau/about/FaqIItem.kt). There exists many ways to make a wrapper allowing for expansions, and here is [my implementation](https://github.com/AllanWang/KAU/blob/dev/core/src/main/kotlin/ca/allanwang/kau/ui/views/CollapsibleViewDelegate.kt)

**Comment by markic22** [comment]
Thanks @mikepenz for reference my issue further.

Damn @AllanWang, I was hoping for some magic solution, with which I could use FastAdapter without further issue :D. I will take a look at your implementation. Thanks for you time to check out the problem.
