### ISSUE TITLE
API filter on endlessScroll

### ISSUE THREAD

**Issue by Wouter0100** [mikepenz/FastAdapter#66]
I'm currently implementing the FastAdapter library in my application which has a list of messages received from an API. I'd like to implement the endlessScroll search with this API instead of the [current loaded messages](https://github.com/mikepenz/FastAdapter/blob/4d33dc516c668f875d2f15e8fb9d6657c0d9cdaf/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.java#L77-L84). Is there any way to do this within the FastAdapter library I could use or you recommend to use?

Thanks.

**Comment by mikepenz** [comment]
@Wouter0100 the `Filter`-API will filter out the current list of items. It can't be used if your items are loaded just while scrolling. 

In your case you will have to implement a search on your API and if the user filters you will have to retrieve the filtered data from the API. 

The problem is that filtering client side won't work as long as you do not already have all elements available.
