### ISSUE TITLE
Visibility property of different items

### ISSUE THREAD

**Issue by gmgunderground** [mikepenz/FastAdapter#693]
Hi, I have a strange behavior with my items, suppose there are two TextView (TV1 and TV2) for each row item, if I scroll down until I find a TV1 that has visibility is GONE (TV1 is gone correctly) and now I scroll up one item again the new item on the top has the TV1 visibility to GONE, and this is not right! seams that is used for the new view the last view used for the last item with the same properties set. I'm using version 3.2.7 of the library and all code is executed inside UI thread. All view properties are changed inside bindView()

**Comment by FabianTerhorst** [comment]
Hi,

you see that behavior because the recyclerview is, as the naming guesses, recycling used views. When you are changing the state of the views that got loaded from the layout inflater and you wanna restore the original state you need to do that in unbindView. For example you would set both textviews to visible there when there are visible in the layout xml as well. This is only required when you change the state programmatically in bindView.

**Comment by gmgunderground** [comment]
Hi, thank you, your reasoning have sense, now all is clear and app it's working fine.
