### ISSUE TITLE
implement data binding

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#70]
thanks for you great and superfast library !

do you plan to implement [data binding](http://developer.android.com/tools/data-binding/guide.html) features in this library ?

thanks

**Comment by mattiasbe** [comment]
Could you clarify what features exactly @DJafari ? Databinding item views works fine with FastAdapter.

**Comment by DJafari** [comment]
@mattiasbe see data binding link.

with data binding we can set variable in xml, in fastadapter it isn't .

**Comment by mikepenz** [comment]
@mattiasbe you use **databinding** with the `FastAdapter`?

**Comment by mattiasbe** [comment]
Yes @DJafari  and @mikepenz . There is nothing special about the adapters for data binding? Just call the DataBindingUtil.bind(view) as usual in the viewholder constructor and define the xml layout files as per databinding as usual. Do the actual binding in bindView, again as usual.
That's why I'm curious about if there are any special neat ideas/shortcuts/helpers @DJafari  is thinking about that would be suitable for FastAdapter.

An example, extract from an Item I'm using (could use `this` instead of `getModel()` if suitable I guess):


    ...

    @Override
    public void bindView(ViewHolder viewHolder) {
        super.bindView(viewHolder);
        viewHolder.binding.setWorkout(getModel());
        viewHolder.binding.executePendingBindings();
    }

    ...

    protected static class ViewHolder extends RecyclerView.ViewHolder {
        private WorkoutBinding binding;

        public ViewHolder(View view) {
            super(view);
            binding = DataBindingUtil.bind(view);
            ...

**Comment by mikepenz** [comment]
@mattiasbe might fit as an additional sample (even if it is nothing complex) but still helpful for people ;)

**Comment by mattiasbe** [comment]
Sure, I'm just saying it's exactly like normal data binding for a RecyclerView and view holder.

**Comment by mikepenz** [comment]
@mattiasbe yes I konw. But it seems that people think there's a big difference.

**Comment by DJafari** [comment]
@mattiasbe your example is helpfull, thanks for your help .

and thanks again from @mikepenz  for this great library and sure best support.

**Comment by mikepenz** [comment]
@mattiasbe , @DJafari thanks

**Comment by BobOtike** [comment]
@mattiasbe I just stumbled upon this issue since I also want to use the FastAdapter with databinding. I was using this library before: [https://github.com/evant/binding-collection-adapter](url), but it is lacking some features like custom `ViewHolder`s for example. I was just just wondering about your example, how do you retrieve the correct `Workout` for any given position in `getModel`? It would be nice if you could elaborate on that. 

As far as neat ideas/shortcuts go, the other library I referenced offers the possibility to bind the whole item collection to the `RecyclerView` and takes care of the proper bindings in detail for every `ViewHolder` from that, that's exactly why I'm not entirely sure of how to do that^^

**Comment by BobOtike** [comment]
Nevermind @mattiasbe, I realized I can simply wrap my model inside my `AbstractItem` and that's about it. Guess it was too early in the morning and I missed the forest for the trees ;) 

But maybe @mikepenz is interested in the feature I mentioned as a suggestion related to the original purpose of this issue.

**Comment by nikitamarysolomanpvt** [comment]
could anybody send a sample code for expandable listview with databinding...?
