### ISSUE TITLE
Adapter contains multiple objects 

### ISSUE THREAD

**Issue by hmedat2008** [mikepenz/FastAdapter#76]
I'm try to use adapter that contains Object A,B,C and D for example, 

But I got this Exception

java.lang.ClassCastException: A$ViewHolder cannot be cast to B$ViewHolder

**Comment by mikepenz** [comment]
@hmedat2008 I assume you talk about having an adapter with 4 different Item's right?

Do those items have different `type`s?
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L105

Do all have their own `ViewHolder`?
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L163

Does the generic definition define the correct type?
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L28

**Comment by mikepenz** [comment]
I will close this for now as it seems to be a problem with the items, rather than the library. We can keep up the discussion in here. 

Please make sure first that the above things are done correctly for the items. 


The `AdvancedSample` for example contains different items in one list
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/AdvancedSampleActivity.java
