### ISSUE TITLE
Add isExpanded shortcut

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#806]
I'm looking through the code and I see a lot of 

`(item as? IExpandable<*>)?.isExpanded)` calls.

I think you'd be better off just attaching

```kt
val GenericItem.isExpanded: Boolean
    get() = (this as? IExpandable<*>)?.isExpanded == true
```

and clean up some of the library code

**Comment by mikepenz** [comment]
@AllanWang I don't think we should do this, as it would result in the "isExpanded" function being available for all items, even though they might not be expandable. This could result in non expected behavior. 

If only kotlin offered "library internal" (e.g. across multiple modules) as it would be nice to have such a convenient function just available within the library, but not show up for SDK users.

**Comment by AllanWang** [comment]
1. Having an internal function within just the expanded module would probably already be better. Most of the logic is there anyways.
2. If the cast fails, `isExpanded` would return false. Wouldn't that be fair?
3. If it is added publicly to the expanded module, only those who use that module would receive the extension. And based on #2, I think the function's purpose is accurately represented in the name

**Comment by FabianTerhorst** [comment]
The problem is none expandable items shouldn't have a ```isExpanded``` property visible for the user.

**Comment by AllanWang** [comment]
Okay then should we just have an internal method then?
