### ISSUE TITLE
How to handle multiple countdown timers in RecyclerView?

### ISSUE THREAD

**Issue by cristarra** [mikepenz/FastAdapter#812]
I use the Java library && AppCompat | v3.2.9, I want to make a countdown on each recyclerview item like they discussed here https://stackoverflow.com/questions/32257586/how-to-handle-multiple-countdown-timers-in-recyclerview

I tried adding to the Activity, handler and runnable to update the recyleview every 1 second using the code below but the results are not smooth:

`
mHandler=new Handler();
mRunnable = () -> {
   itemAdapter.clear();
   itemAdapter.add(LIST);
   mHandler.postDelayed(mRunnable, 1000);
};
mHandler.post(mRunnable);
`

## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by pablichjenkov** [comment]
Above approach will overkill the recyclerView since it will recreate all the items every one second. It implies vast memory consumption and also time computing the geometry of each item to render on screen.
You have two options:
1- Update just the model that is inside your LIST and call **itemAdapter.notifyDataSetChange()**

2- Create a function in your custom item class called updateTime(). Your item has a ViewHolder, so you will reference the TextView you want to update. Now, how the item class gets notified of the time update. You will need to subscribe to your Timer Handler when the item is created. Don't forget to unsubscribe when the item is recycled.

**Comment by mikepenz** [comment]
This is not specific to this library. 

RecyclerView adapters have a concept to notify the RV adapter with a payload. 

Please check out the RecyclerView javadoc for how to use payloads. 

(basically notify an item at a specific position with the payload, and then update the specific view inside your item based on the info your payload told you. )
