### ISSUE TITLE
Item can't be inferred from fun <Item : GenericItem, A : IAdapter<*>> with(adapters: Collection<A>?)

### ISSUE THREAD

**Issue by alexeyr** [mikepenz/FastAdapter#838]
In the other two overloads 

    fun <Item : GenericItem, A : IAdapter<Item>> with(adapter: A)
    fun <Item : GenericItem, A : IAdapter<*>> with(adapters: Collection<A>?, extensions: Collection<IAdapterExtension<Item>>?)

`Item` can be inferred from parameters.

Given the cast 

https://github.com/mikepenz/FastAdapter/blob/14ed13dc73e82d55420f1b30539d4ad8097da46b/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt#L935

it seems like:

1. `A` should extend `IAdapter<Item>`, not `IAdapter<*>` in all overloads. 
2. Thanks to `Collection` covariance, `A` type parameter is actually unnecessary in all overloads, it should be just
```
@JvmStatic
fun <Item : GenericItem> with(adapter: IAdapter<Item>)
@JvmOverloads 
@JvmStatic
fun <Item : GenericItem> with(adapters: Collection<IAdapter<Item>>?, extensions: Collection<IAdapterExtension<Item>>? = null)
```

**Comment by mikepenz** [comment]
Doing these changes will prevent situations in which we would love to have a list of different adapters with different item types:

![image](https://user-images.githubusercontent.com/1476232/70232889-b2f4b380-175d-11ea-8435-018e44fc5ab5.png)

**Comment by alexeyr** [comment]
Then perhaps `fun <Item : GenericItem> with(adapter: IAdapter<out Item>)`?

**Comment by mikepenz** [comment]
@alexeyr I suppose you meant to add the out for the collection usecase of the `with` function. 

At least from the sample's perspective things seem to compile and run. but require also adjustments to apps using the `FastAdapter` due to the changed definition of the methods. 

This means this is a more substantial adjustment and will require further consideration from more people. To see if it affects developers / apps in other ways we might miss here. 

If you want to try and compile it yourself. here's the branch: https://github.com/mikepenz/FastAdapter/tree/feature/fix_838

**Comment by mikepenz** [comment]
@AllanWang you might also have an opinion on these changes :)

**Comment by mikepenz** [comment]
There's now an open PR scheduled for v5 of the FastAdapter
