### ISSUE TITLE
README sample code section 3.1outdated

### ISSUE THREAD

**Issue by Sebastiaan-Alvarez-Rodriguez** [mikepenz/FastAdapter#868]
As noted in issue #666, the README example on selectionExtension is outdated.
It hasn't been changed in 2 years, showing a deprecated way of getting the selectionExtension.

Please update the documentation, so people do not have to search issues for the correct usage.

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Oops just noticed that there appear that README no longer covers java v4/5.
However, library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt does not contain a getSelectionExtension function. So the README code is also outdated for kotlin v4/5 library versions

**Comment by mikepenz** [comment]
Based on the v4/v5 code there is the `getSelectExtension()` function. It is an extension function and added via the select extension:

https://github.com/mikepenz/FastAdapter/blob/fde5ff985ebf1baed57c97f1329fa53408ce4719/library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt#L29-L35

So the code should be correct.

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Thanks for showing where the function resides in the framework!
I just converted my code to kotlin and found out that this function then is callable.

This is completely new behaviour for me: I always thought that Kotlin is a drop-in for Java, meaning I would be able to call Java from Kotlin and Kotlin from Java.

Appearently, this is not the case (with this library at least).

Your readme is up to date then, and seems like I got some reformatting to do and Kotlin to learn.

**Comment by mikepenz** [comment]
@Sebastiaan-Alvarez-Rodriguez that is in general true. that java and kotlin are interoperable.
But due to the fact that v3 was already very stable we chose to go full kotlin first. that means various APIs are only nice to use via kotlin and may be super ugly from java. this allows us to make much more bold and simpler API choices than if we still had to support java too. and to be honest. with Google going kotlin first too it is absolutely recommend to start all new apps with kotlin :)  

If you want to go with java please refer to v3 of this library. 

See here for the versions which are best for which setup: https://github.com/mikepenz/FastAdapter#latest-releases
