### ISSUE TITLE
RecycleView incorrect width child by scroll

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/FastAdapter#87]
Stable problem in RecycleView, but I feel what it can be fixed thow fastAdapter or custom layoutManager.

The problem is in measured width of item.
It's reproduce by fast scroll up - down.

On screen see last two items.

By screens:
1 - enter to screen
2 - some scroll to top
3 - return to start position (scroll to bottom)

steps 2-3 need do sometimes.

![1](https://cloud.githubusercontent.com/assets/1124827/13923416/970ca0b2-ef91-11e5-8947-f8e6b82f89cd.png)
![2](https://cloud.githubusercontent.com/assets/1124827/13923415/970b94a6-ef91-11e5-9cad-5b0c21f7b34e.png)
![3](https://cloud.githubusercontent.com/assets/1124827/13923414/970b8650-ef91-11e5-9aed-dc0a55a0e2d1.png)

**Comment by mikepenz** [comment]
@gromiloff the issue is not related to the `FastAdapter`. It might be related to the `Item` you have created.

How do you define the width of the items? Items are reused. "Recycled" when you scroll. So you might need to invalidate the view when it is bound again. 

I do not know if you can fix it with a custom `LayoutManager`. You might need to ask this on `StackOverFlow`. It might also be an issue related to the latest support libraries.
