### ISSUE TITLE
Question: is there a way to close the swipe menu?

### ISSUE THREAD

**Issue by kenargo** [mikepenz/FastAdapter#938]
I'd like to programmatically close the swipe panel after the user has performed and action but I haven't found a way to do that currently.

**Comment by mikepenz** [comment]
That's a limitation of the `ItemTouchHelper`. But according to stackOverflow the best approach is to do: https://stackoverflow.com/a/32159154

Otherwise I think if you would be able to access protected methods from it, it would be done by calling this method with null

![image](https://user-images.githubusercontent.com/1476232/97673708-812ebe80-1a8c-11eb-8c6e-9dd560a466b0.png)
